In [2]:
import pandas as pd
import numpy as np
import os

import tensorflow as tf
from tensorflow.keras import layers, losses, models, optimizers

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from numpy.lib.stride_tricks import sliding_window_view
from sklearn.preprocessing import MinMaxScaler

import vae as V

def data_scaling(data):             #스케일러, main
    scaler = MinMaxScaler()
    data = scaler.fit_transform(data)

    return data


def data_sliding(data, n_features, Time_window): #데이터 밀기, main
    # reshape_num = data.shape[0] - Time_window + 1
    data = sliding_window_view(data, (Time_window, n_features))
    #   data = data.reshape(reshape_num, Time_window, n_features) <-필요없음

    return data


def data_load_processing(FILENAME, Time_window=None): #데이터 로딩 및 스케일러 사용, main
    df = pd.read_csv(FILENAME)
    df = df.drop(['Time'], axis=1)
    n_features = df.shape[1]
    x_train, x_test = train_test_split(df, test_size=0.9, shuffle=False)
    #x_validation, x_test = train_test_split(x_test, test_size=0.5, shuffle=False)

    x_train = data_scaling(x_train)
    x_test = data_scaling(x_test)
    #x_validation = data_scaling(x_validation)

    x_train = data_sliding(x_train, n_features, Time_window)
    x_test = data_sliding(x_test, n_features, Time_window)
    #x_validation = data_sliding(x_validation, n_features, Time_window)

    return x_train, x_test #, x_validation


def sampling(inputs):
    z_mean, z_log_var = inputs
    batch = tf.shape(z_mean)[0]
    dim = tf.shape(z_mean)[1]
    epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
    return z_mean + tf.exp(0.5 * z_log_var) * epsilon

class VAE(tf.keras.Model):
    def __init__(self, encoder, decoder, **kwargs):
        super(VAE, self).__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.total_loss_tracker = tf.keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = tf.keras.metrics.Mean(
            name="reconstruction_loss"
        )
        self.kl_loss_tracker = tf.keras.metrics.Mean(name="kl_loss")

    @property
    def metrics(self):
        return [
            self.total_loss_tracker,
            self.reconstruction_loss_tracker,
            self.kl_loss_tracker,
        ]

    def train_step(self, data):
        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)
            reconstruction_loss = tf.reduce_mean(
                tf.reduce_sum(
                    tf.keras.losses.binary_crossentropy(data, reconstruction), axis=(1, 2)
                )
            )
            kl_loss = -0.5 * (1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var))
            kl_loss = tf.reduce_mean(tf.reduce_sum(kl_loss, axis=1))
            total_loss = reconstruction_loss + kl_loss
        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))
        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        self.kl_loss_tracker.update_state(kl_loss)
        return {
            "loss": self.total_loss_tracker.result(),
            "reconstruction_loss": self.reconstruction_loss_tracker.result(),
            "kl_loss": self.kl_loss_tracker.result(),
        }


def vae_model(input_shape, latent_dim, kernel_size, strides, padding,act):
    inputs = tf.keras.Input(shape=input_shape)
    h = layers.Conv2D(32, kernel_size=kernel_size, strides=strides, padding=padding, activation='relu',
                      name="conv1", data_format="channels_first")(inputs)
    h = layers.Conv2D(64, kernel_size=kernel_size, strides=strides, padding=padding, activation='relu',
                      name="conv2", data_format="channels_first")(h)
    h = layers.Conv2D(128, kernel_size=kernel_size, strides=strides, padding=padding, activation='relu',
                      name="conv3", data_format="channels_first")(h)
    shape_save = h.get_shape().as_list()
    h = layers.Flatten()(h)
    h = layers.Dense(16, activation="relu")(h)

    # vae
    z_mean = layers.Dense(latent_dim, name='z_mean')(h)
    z_log_var = layers.Dense(latent_dim, name='z_log_var')(h)
    z = sampling([z_mean, z_log_var])
    encoder = tf.keras.Model(inputs, [z_mean, z_log_var, z], name='encoder')

    # decoder
    latent_inputs = tf.keras.Input(shape=(latent_dim,))
    h = layers.Dense(shape_save[1] * shape_save[2] * shape_save[3], activation="relu")(latent_inputs)
    h = layers.Reshape((shape_save[1], shape_save[2], shape_save[3]))(h)
    h = layers.Conv2DTranspose(64, kernel_size=kernel_size, strides=strides, padding=padding, activation='relu',
                               data_format="channels_first")(h)
    h = layers.Conv2DTranspose(32, kernel_size=kernel_size, strides=strides, padding=padding, activation='relu',
                               data_format="channels_first")(h)
    decoder_outputs = layers.Conv2DTranspose(1,kernel_size=kernel_size, strides=strides, padding=padding, activation=act,
                                             data_format="channels_first")(h)
    decoder = tf.keras.Model(latent_inputs, decoder_outputs, name="decoder")

    return encoder, decoder

def lstm_preprocess(latent_z, seq_length):
    reshape_num = latent_z.shape[0] - seq_length + 1
    slide_z = sliding_window_view(latent_z, (seq_length, latent_z.shape[1]))
    slide_z = slide_z.reshape(reshape_num, seq_length, latent_z.shape[1])
    slide_z = slide_z[:-1]

    dataY = []
    for i in range(0, len(latent_z) - seq_length):
        _y = latent_z[i + seq_length]  # 다음 나타날 z(정답)
        dataY.append(_y)  # dataY 리스트에 추가
    dataY = np.array(dataY)
    
    return slide_z, dataY
    
    
def lstm_model(seq_length, latent_dim, lstm_z):
    
    inputs = tf.keras.Input(shape=(seq_length, latent_dim))
    h = layers.LSTM(32, activation="relu", name='lstm1')(inputs)
    lstm_outputs = layers.Dense(latent_dim, activation='sigmoid')(h)
    lstm = tf.keras.Model(inputs, lstm_outputs, name='lstm')
    lstm.compile(loss='mse', optimizer=tf.keras.optimizers.Adam())
    lstm.fit(lstm_z, dataY, epochs=5, batch_size=256)
    lstm_results = lstm.predict(lstm_z)

    return lstm_results
    
    
if __name__ == '__main__':
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
    config = tf.compat.v1.ConfigProto()
    config.gpu_options.allow_growth = True
    session = tf.compat.v1.Session(config=config)

    #---------------------------------사용자 설정 변수---------------------------------------
    FILENAME = "BTC_USDT.csv"
    Time_window = 8
    latent_dim = 2
    #-------------------------------------------------------------------------------------

    #데이터 로딩
    x_train, x_test= data_load_processing(FILENAME, Time_window=Time_window)


In [ ]:
#VAE_model
latent_dim = 2
input_shape = (1, 8, 54)
kernel_size = (2,4)
strides = (2,2)
padding = "valid"
act = "sigmoid"
encoder, decoder = vae_model(input_shape, latent_dim, kernel_size, strides, padding,act)

#VAE
vae = V.VAE(encoder, decoder)
vae.compile(optimizer=tf.keras.optimizers.Adam())
vae.fit(x_train, epochs=1, batch_size=128)

z_mean_, z_log_var_, latent_z = vae.encoder.predict(x_train)
#------------------------------------------------------------------------------------------
seq_length = 8

lstm_z, dataY = lstm_preprocess(latent_z, seq_length)

lstm_results = lstm_model(seq_length, latent_dim, lstm_z)

decoder_output = vae.decoder.predict(lstm_results)

In [3]:
#VAE_model
latent_dim = 2
input_shape = (1, 8, 54)
kernel_size = (2,4)
strides = (2,2)
padding = "valid"
act = "sigmoid"
encoder, decoder = vae_model(input_shape, latent_dim, kernel_size, strides, padding,act)
encoder.summary()

#VAE
vae = V.VAE(encoder, decoder)
vae.compile(optimizer=tf.keras.optimizers.Adam())
vae.fit(x_train, epochs=10, batch_size=128)

z_mean_, z_log_var_, latent_z = vae.encoder.predict(x_train)

decoded_latent_z = vae.decoder.predict(latent_z)

def MAPE(y_test, y_pred):
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100 
    
MAPE(x_train[0][0][0], decoded_latent_z[0][0][0])

Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 1, 8, 54)]   0                                            
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 32, 4, 26)    288         input_1[0][0]                    
__________________________________________________________________________________________________
conv2 (Conv2D)                  (None, 64, 2, 12)    16448       conv1[0][0]                      
__________________________________________________________________________________________________
conv3 (Conv2D)                  (None, 128, 1, 5)    65664       conv2[0][0]                      
____________________________________________________________________________________________

43.405698779786455

In [4]:
x_train[0][0][0]

array([2.92028172e-01, 2.90334511e-01, 2.94325406e-01, 2.91690876e-01,
       1.28034781e-02, 2.91970143e-01, 1.70846712e-02, 2.91319238e-01,
       2.01296969e-02, 4.47492299e-01, 2.36533311e-01, 3.66674647e-01,
       3.92146587e-01, 2.91061150e-01, 2.12365833e-02, 2.91134819e-01,
       2.79011400e-02, 3.60360194e-01, 1.27683809e-01, 3.65558665e-01,
       2.11723599e-01, 2.91124649e-01, 3.42660671e-02, 2.90319558e-01,
       2.98881262e-02, 3.48278646e-01, 6.07620474e-02, 3.35166460e-01,
       1.17714478e-01, 2.85898890e-01, 2.37780000e-02, 2.85868523e-01,
       3.21074999e-02, 2.99450752e-01, 5.12985089e-02, 2.97449067e-01,
       6.24664374e-02, 2.82898658e-01, 5.55299442e-02, 2.84263507e-01,
       4.31056906e-02, 3.02565338e-01, 2.62291760e-02, 3.02324704e-01,
       4.48243776e-02, 5.33293333e-01, 3.61499602e-02, 9.99928230e-01,
       5.65686608e-01, 4.23772617e-04, 4.13801998e-01, 2.49842430e-01,
       9.89829098e-01, 3.75898567e-02])

In [5]:
decoded_latent_z[0][0][0]

array([4.18099493e-01, 4.16757941e-01, 4.19703335e-01, 4.16076064e-01,
       2.34368835e-02, 4.14020598e-01, 3.65704075e-02, 4.12013024e-01,
       4.36796322e-02, 4.51304018e-01, 2.13603467e-01, 3.78624111e-01,
       3.24392319e-01, 4.15806562e-01, 4.73525599e-02, 4.13674682e-01,
       5.92509545e-02, 3.72370899e-01, 1.19508751e-01, 3.83469194e-01,
       1.89862415e-01, 4.13511395e-01, 6.32721782e-02, 4.11593884e-01,
       6.46123812e-02, 3.75601947e-01, 7.01481327e-02, 3.54057491e-01,
       1.12239227e-01, 4.10392970e-01, 7.38411248e-02, 4.08952415e-01,
       7.90221840e-02, 3.03779602e-01, 4.20528688e-02, 3.03779006e-01,
       5.77551015e-02, 4.08249438e-01, 1.01201601e-01, 4.09710675e-01,
       1.01965584e-01, 3.01319063e-01, 3.16159986e-02, 3.04298580e-01,
       4.39890623e-02, 5.14957309e-01, 2.18226518e-02, 9.67293024e-01,
       5.63111305e-01, 2.69506883e-04, 4.59070802e-01, 4.96765345e-01,
       4.72669631e-01, 4.95276377e-02], dtype=float32)

In [6]:
#VAE_model
latent_dim = 2
input_shape = (1, 8, 54)
kernel_size = (2,4)
strides = (2,2)
padding = "valid"
act = "tanh"
encoder, decoder = vae_model(input_shape, latent_dim, kernel_size, strides, padding,act)
encoder.summary()

#VAE
vae = V.VAE(encoder, decoder)
vae.compile(optimizer=tf.keras.optimizers.Adam())
vae.fit(x_train, epochs=10, batch_size=128)

z_mean_, z_log_var_, latent_z = vae.encoder.predict(x_train)

decoded_latent_z = vae.decoder.predict(latent_z)

def MAPE(y_test, y_pred):
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100 
    
MAPE(x_train[0][0][0], decoded_latent_z[0][0][0])

Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 1, 8, 54)]   0                                            
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 32, 4, 26)    288         input_3[0][0]                    
__________________________________________________________________________________________________
conv2 (Conv2D)                  (None, 64, 2, 12)    16448       conv1[0][0]                      
__________________________________________________________________________________________________
conv3 (Conv2D)                  (None, 128, 1, 5)    65664       conv2[0][0]                      
____________________________________________________________________________________________

182.5979424989267

In [7]:
x_train[0][0][0]

array([2.92028172e-01, 2.90334511e-01, 2.94325406e-01, 2.91690876e-01,
       1.28034781e-02, 2.91970143e-01, 1.70846712e-02, 2.91319238e-01,
       2.01296969e-02, 4.47492299e-01, 2.36533311e-01, 3.66674647e-01,
       3.92146587e-01, 2.91061150e-01, 2.12365833e-02, 2.91134819e-01,
       2.79011400e-02, 3.60360194e-01, 1.27683809e-01, 3.65558665e-01,
       2.11723599e-01, 2.91124649e-01, 3.42660671e-02, 2.90319558e-01,
       2.98881262e-02, 3.48278646e-01, 6.07620474e-02, 3.35166460e-01,
       1.17714478e-01, 2.85898890e-01, 2.37780000e-02, 2.85868523e-01,
       3.21074999e-02, 2.99450752e-01, 5.12985089e-02, 2.97449067e-01,
       6.24664374e-02, 2.82898658e-01, 5.55299442e-02, 2.84263507e-01,
       4.31056906e-02, 3.02565338e-01, 2.62291760e-02, 3.02324704e-01,
       4.48243776e-02, 5.33293333e-01, 3.61499602e-02, 9.99928230e-01,
       5.65686608e-01, 4.23772617e-04, 4.13801998e-01, 2.49842430e-01,
       9.89829098e-01, 3.75898567e-02])

In [8]:
decoded_latent_z[0][0][0]

array([ 0.41766277,  0.41889974,  0.42084754,  0.4214852 ,  0.02413475,
        0.42367056,  0.03628674,  0.42416644,  0.04411514,  0.46039099,
        0.21106328,  0.38851222,  0.32216308,  0.42364836,  0.04456185,
        0.425455  ,  0.05890395,  0.37977713,  0.11526326,  0.3932582 ,
        0.18512012,  0.42150375,  0.05983473,  0.42333716,  0.06334583,
        0.38370833,  0.06736528,  0.36373365,  0.10686415,  0.420181  ,
        0.06938571,  0.42074898,  0.07790724,  0.31114632,  0.03963118,
        0.31525144,  0.05633463,  0.41982535,  0.09810513,  0.42049846,
        0.10273921,  0.31012365,  0.03128133,  0.318601  ,  0.04457743,
        0.52423596,  0.0197697 ,  0.96816665,  0.56901735, -0.03135506,
        0.45597643,  0.51712155,  0.4935831 ,  0.05497451], dtype=float32)

In [9]:
#VAE_model
latent_dim = 2
input_shape = (1, 8, 54)
kernel_size = (2,4)
strides = (2,2)
padding = "valid"
act = "linear"
encoder, decoder = vae_model(input_shape, latent_dim, kernel_size, strides, padding,act)
encoder.summary()

#VAE
vae = V.VAE(encoder, decoder)
vae.compile(optimizer=tf.keras.optimizers.Adam())
vae.fit(x_train, epochs=10, batch_size=128)

z_mean_, z_log_var_, latent_z = vae.encoder.predict(x_train)

decoded_latent_z = vae.decoder.predict(latent_z)

def MAPE(y_test, y_pred):
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100 
    
MAPE(x_train[0][0][0], decoded_latent_z[0][0][0])

Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            [(None, 1, 8, 54)]   0                                            
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 32, 4, 26)    288         input_5[0][0]                    
__________________________________________________________________________________________________
conv2 (Conv2D)                  (None, 64, 2, 12)    16448       conv1[0][0]                      
__________________________________________________________________________________________________
conv3 (Conv2D)                  (None, 128, 1, 5)    65664       conv2[0][0]                      
____________________________________________________________________________________________

447.5199553432723

In [10]:
x_train[0][0][0]

array([2.92028172e-01, 2.90334511e-01, 2.94325406e-01, 2.91690876e-01,
       1.28034781e-02, 2.91970143e-01, 1.70846712e-02, 2.91319238e-01,
       2.01296969e-02, 4.47492299e-01, 2.36533311e-01, 3.66674647e-01,
       3.92146587e-01, 2.91061150e-01, 2.12365833e-02, 2.91134819e-01,
       2.79011400e-02, 3.60360194e-01, 1.27683809e-01, 3.65558665e-01,
       2.11723599e-01, 2.91124649e-01, 3.42660671e-02, 2.90319558e-01,
       2.98881262e-02, 3.48278646e-01, 6.07620474e-02, 3.35166460e-01,
       1.17714478e-01, 2.85898890e-01, 2.37780000e-02, 2.85868523e-01,
       3.21074999e-02, 2.99450752e-01, 5.12985089e-02, 2.97449067e-01,
       6.24664374e-02, 2.82898658e-01, 5.55299442e-02, 2.84263507e-01,
       4.31056906e-02, 3.02565338e-01, 2.62291760e-02, 3.02324704e-01,
       4.48243776e-02, 5.33293333e-01, 3.61499602e-02, 9.99928230e-01,
       5.65686608e-01, 4.23772617e-04, 4.13801998e-01, 2.49842430e-01,
       9.89829098e-01, 3.75898567e-02])

In [11]:
decoded_latent_z[0][0][0]

array([ 0.40881914,  0.39995444,  0.40690887,  0.40078083,  0.02096081,
        0.39738703,  0.03592284,  0.39897865,  0.0413378 ,  0.4335424 ,
        0.20433599,  0.36745787,  0.3132404 ,  0.396187  ,  0.04363459,
        0.4022055 ,  0.05569618,  0.3607217 ,  0.11077671,  0.37405246,
        0.179897  ,  0.39961293,  0.05630418,  0.40832385,  0.05935341,
        0.36549485,  0.06315521,  0.34677988,  0.10411687,  0.39999345,
        0.06772111,  0.40509856,  0.07314827,  0.29394725,  0.03716065,
        0.29879963,  0.05290093,  0.4000028 ,  0.09358127,  0.40449795,
        0.09611005,  0.29249233,  0.02943386,  0.30217013,  0.04270905,
        0.5113592 ,  0.02265958,  0.96486014,  0.57043505, -0.09322964,
        0.45858902,  0.4883399 ,  0.4790087 ,  0.04133465], dtype=float32)