In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from numpy.lib.stride_tricks import sliding_window_view
from sklearn.preprocessing import MinMaxScaler

In [4]:
df=pd.read_csv("KRW-XRP_min_1_2018-03-01.csv")

In [40]:
df=pd.read_csv("KRW-BTC_min_1_2018-03-01.csv")

In [5]:
df

Time    Open    High     Low   Close         Volume  \
0        2018-03-01 02:07:00  1025.0  1025.0  1020.0  1020.0   30403.115208   
1        2018-03-01 02:08:00  1020.0  1020.0  1020.0  1020.0   15791.015794   
2        2018-03-01 02:09:00  1020.0  1025.0  1020.0  1025.0    4374.860175   
3        2018-03-01 02:10:00  1025.0  1025.0  1020.0  1025.0   10102.455756   
4        2018-03-01 02:11:00  1025.0  1025.0  1025.0  1025.0   15094.641216   
...                      ...     ...     ...     ...     ...            ...   
1421781  2021-02-28 23:55:00   476.0   477.0   475.0   477.0  192911.922684   
1421782  2021-02-28 23:56:00   477.0   478.0   477.0   477.0  394465.742476   
1421783  2021-02-28 23:57:00   477.0   478.0   477.0   477.0  133548.495572   
1421784  2021-02-28 23:58:00   477.0   478.0   477.0   477.0  121931.153385   
1421785  2021-02-28 23:59:00   478.0   480.0   478.0   480.0  743574.101981   

         close_ma5     volume_ma5   close_ema5    volume_ema5  ...  \
0           1022.0    9027.902562  1021.045493   13741.553437  ...   
1           1021.0   12018.952433  1020.696996   14424.707556  ...   
2           1021.0   12802.556739  1022.131330   11074.758429  ...   
3           1022.0   14746.694447  1023.087554   10750.657538  ...   
4           1023.0   15153.217630  1023.725036   12198.652097  ...   
...            ...            ...          ...            ...  ...   
1421781      476.6  207596.897726   476.668676  262513.068415  ...   
1421782      476.6  271860.801871   476.779117  306497.293102  ...   
1421783      476.6  258829.559628   476.852745  248847.693925  ...   
1421784      476.8  234643.876395   476.901830  206542.180412  ...   
1421785      477.6  317286.283219   477.934553  385552.820935  ...   

         volume_ema120_ratio  open_lastclose_ratio  high_close_ratio  \
0                   2.536958              0.004902          0.004902   
1                   0.808195              0.000000          0.000000   
2                  -0.494244              0.000000          0.000000   
3                   0.164187              0.000000          0.000000   
4                   0.715469              0.000000          0.000000   
...                      ...                   ...               ...   
1421781            -0.625006              0.000000          0.000000   
1421782            -0.230245              0.000000          0.002096   
1421783            -0.736171              0.000000          0.002096   
1421784            -0.756061              0.000000          0.002096   
1421785             0.475724              0.002096          0.000000   

         low_close_ratio  close_lastclose_ratio  volume_lastvolume_ratio  \
0               0.000000               0.000000                 1.327596   
1               0.000000               0.000000                -0.480612   
2              -0.004878               0.004902                -0.722953   
3              -0.004878               0.000000                 1.309207   
4               0.000000               0.000000                 0.494156   
...                  ...                    ...                      ...   
1421781        -0.004193               0.002101                -0.416059   
1421782         0.000000               0.000000                 1.044797   
1421783         0.000000               0.000000                -0.661445   
1421784         0.000000               0.000000                -0.086990   
1421785        -0.004167               0.006289                 5.098311   

             MACD        RSI           OBV           MFI  
0       -0.027162  50.000000  6.794597e+04  1.893647e+09  
1       -0.185047  50.000000  6.794597e+04  9.144790e+09  
2        0.364664  66.666667  7.232083e+04  8.890860e+09  
3        0.690107  66.666667  7.232083e+04  8.890860e+09  
4        0.856350  66.666667  7.232083e+04  8.890860e+09  
...           ...        ...           ...           ...  
1421781 -0.189340  71.428571  7.514102e+08 

In [6]:
df=df.drop(['Time'],axis=1)

In [7]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'close_ma5', 'volume_ma5',
       'close_ema5', 'volume_ema5', 'close_ma5_ratio', 'volume_ma5_ratio',
       'close_ema5_ratio', 'volume_ema5_ratio', 'close_ma10', 'volume_ma10',
       'close_ema10', 'volume_ema10', 'close_ma10_ratio', 'volume_ma10_ratio',
       'close_ema10_ratio', 'volume_ema10_ratio', 'close_ma20', 'volume_ma20',
       'close_ema20', 'volume_ema20', 'close_ma20_ratio', 'volume_ma20_ratio',
       'close_ema20_ratio', 'volume_ema20_ratio', 'close_ma60', 'volume_ma60',
       'close_ema60', 'volume_ema60', 'close_ma60_ratio', 'volume_ma60_ratio',
       'close_ema60_ratio', 'volume_ema60_ratio', 'close_ma120',
       'volume_ma120', 'close_ema120', 'volume_ema120', 'close_ma120_ratio',
       'volume_ma120_ratio', 'close_ema120_ratio', 'volume_ema120_ratio',
       'open_lastclose_ratio', 'high_close_ratio', 'low_close_ratio',
       'close_lastclose_ratio', 'volume_lastvolume_ratio', 'MACD', 'RSI',
       'OBV', 'MF

In [44]:
Time_window=5

In [27]:
x_train.shape

(1090462, 29)

In [15]:
x_train, x_test = train_test_split(df, test_size=0.3, shuffle=False)
x_validation, x_test = train_test_split(x_test, test_size=0.5, shuffle=False)
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_validation = scaler.fit_transform(x_validation)
x_test = scaler.fit_transform(x_test)


C:\Users\User\anaconda3\lib\site-packages\numpy\lib\stride_tricks.py:307: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  window_shape_array = np.array(window_shape)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [30]:
reshape_num = x_train.shape[0] - Time_window + 1
data = sliding_window_view(x_train, (Time_window, x_train.shape[1]))
data = data.reshape(reshape_num, Time_window, x_train.shape[1])

In [28]:
x_train.shape[0]

1090462

In [93]:
df.shape[1]

29

In [45]:
df_array=np.array(df)

In [46]:
df_array.shape

(1557803, 29)

In [47]:
df_array

array([[ 1.18680000e+07,  1.18820000e+07,  1.18670000e+07, ...,
         5.19083969e+01, -3.56070947e+01,  5.64579216e+01],
       [ 1.18680000e+07,  1.18680000e+07,  1.18600000e+07, ...,
         5.00000000e+01, -3.90989475e+01,  5.67044281e+01],
       [ 1.18600000e+07,  1.18660000e+07,  1.18550000e+07, ...,
         3.94957983e+01, -4.95094147e+01,  4.61711264e+01],
       ...,
       [ 5.12680000e+07,  5.13220000e+07,  5.12680000e+07, ...,
         5.37223340e+01, -8.33615122e+04,  6.22693267e+01],
       [ 5.12730000e+07,  5.13020000e+07,  5.12730000e+07, ...,
         5.74055158e+01, -8.33580797e+04,  6.69180752e+01],
       [ 5.13160000e+07,  5.14990000e+07,  5.13030000e+07, ...,
         6.61403509e+01, -8.33413631e+04,  7.09861641e+01]])

In [48]:
Time_window=5 
reshape_num = df.shape[0]-Time_window+1


In [50]:
reshape_num

1557799

In [54]:
tmp=sliding_window_view(df_array,(Time_window,df.shape[1]))
tmp.shape

(1557799, 1, 5, 29)

In [ ]:
tmp=tmp.reshape(reshape_num,Time_window,df.shape[1])
tmp

In [52]:
tmp.shape

(1557799, 5, 29)

In [81]:
x = np.arange(29*15)
x=x.reshape(15,29)
x

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28],
       [ 29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
         55,  56,  57],
       [ 58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86],
       [ 87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
        100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115],
       [116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144],
       [145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
        158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
    

In [82]:
v = sliding_window_view(x,(3,29))
v=v.reshape(13,3,29)

In [83]:
v[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
        45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
        74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86]])

In [88]:
v[1]

array([[ 29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
         55,  56,  57],
       [ 58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86],
       [ 87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
        100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115]])

In [ ]:
n_inputs = 40*29
n_hidden1 = 300
n_hidden2 = 150
n_hidden3 = n_hidden1
n_outputs = n_inputs

In [108]:
x_train, x_test = train_test_split(tmp, test_size=0.3, shuffle=False, random_state=34)

In [109]:
x_validation , x_test = train_test_split(x_test, test_size=0.5, shuffle=False, random_state=34)

In [110]:
x_train.shape

(1090459, 5, 29)

In [111]:
x_test.shape

(233670, 5, 29)

In [112]:
x_validation.shape

(233670, 5, 29)

In [61]:
import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score, precision_score, recall_score
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from numpy.lib.stride_tricks import sliding_window_view
from sklearn.preprocessing import MinMaxScaler

def data_scaling(data):
    scaler = MinMaxScaler()
    data = scaler.fit_transform(data)

    return data


def data_sliding(data,Time_window):
    print(data.shape)
    reshape_num = data.shape[0] - Time_window + 1
    data = sliding_window_view(data, (Time_window, data.shape[1]))
    print(data.shape)
    data = data.reshape(reshape_num, Time_window, data.shape[3])
    print(data.shape)

    return data

def data_load_processing(FILENAME,Time_window=None):
    df = pd.read_csv(FILENAME)
    df = df.drop(['Time'], axis=1)

    x_train, x_test = train_test_split(df, test_size=0.3, shuffle=False)
    x_validation, x_test = train_test_split(x_test, test_size=0.5, shuffle=False)

    x_train = data_scaling(x_train)
    x_test = data_scaling(x_test)
    x_validation = data_scaling(x_validation)

    x_train = data_sliding(x_train, Time_window)
    x_test  = data_sliding(x_test, Time_window)
    x_validation = data_sliding(x_validation, Time_window)


    return x_train, x_test, x_validation


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    FILENAME = "KRW-BTC_min_1_2018-03-01.csv"
    Time_window = 5
    x_train, x_test, x_validation = data_load_processing(FILENAME, Time_window=Time_window)
    

(1090462, 29)
(1090458, 1, 5, 29)
(1090458, 5, 29)
(233671, 29)
(233667, 1, 5, 29)
(233667, 5, 29)
(233670, 29)
(233666, 1, 5, 29)
(233666, 5, 29)


In [1]:
import pandas as pd
import numpy as np
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
from sklearn.metrics import accuracy_score, precision_score, recall_score
from tensorflow.keras import layers, losses, models, optimizers
from tensorflow.keras.datasets import fashion_mnist

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from numpy.lib.stride_tricks import sliding_window_view
from sklearn.preprocessing import MinMaxScaler


def data_scaling(data):
    scaler = MinMaxScaler()
    data = scaler.fit_transform(data)

    return data


def data_sliding(data, n_features, Time_window):
    reshape_num = data.shape[0] - Time_window + 1
    data = sliding_window_view(data, (Time_window, n_features))
    #   data = data.reshape(reshape_num, Time_window, n_features) <-필요없음

    return data


def data_load_processing(FILENAME, Time_window=None):
    df = pd.read_csv(FILENAME)
    df = df.drop(['Time'], axis=1)
    n_features = df.shape[1]
    x_train, x_test = train_test_split(df, test_size=0.9, shuffle=False)
    #x_validation, x_test = train_test_split(x_test, test_size=0.5, shuffle=False)

    x_train = data_scaling(x_train)
    x_test = data_scaling(x_test)
    #x_validation = data_scaling(x_validation)

    x_train = data_sliding(x_train, n_features, Time_window)
    x_test = data_sliding(x_test, n_features, Time_window)
    #x_validation = data_sliding(x_validation, n_features, Time_window)

    return x_train, x_test #, x_validation


# Press the green button in the gutter to run the script.

class Sampling(layers.Layer):
    """Uses (z_mean, z_log_var) to sample z, the vector encoding a digit."""

    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon


if __name__ == '__main__':
    config = tf.compat.v1.ConfigProto()
    config.gpu_options.allow_growth = True
    session = tf.compat.v1.Session(config=config)

    FILENAME = "KRW-XRP_min_1_2018-03-01.csv"
    Time_window = 8
    x_train, x_test= data_load_processing(FILENAME, Time_window=Time_window)
    #n_features = x_train.shape[1]
    #print(x_train.shape)

    latent_dim = 2

     #encoder
    inputs = tf.keras.Input(shape=(1, 8, 54))
    h = layers.Conv2D(32, kernel_size=(2, 4), strides=(2, 2), padding='valid', activation=tf.keras.activations.relu,
                      name="conv1", data_format="channels_first")(inputs)
    h = layers.Conv2D(64, kernel_size=(2, 4), strides=(2, 2), padding='valid', activation=tf.keras.activations.relu,
                      name="conv2", data_format="channels_first")(h)
    h = layers.Conv2D(128, kernel_size=(2, 4), strides=(2, 2), padding='valid', activation=tf.keras.activations.relu,
                      name="conv3", data_format="channels_first")(h)
    h = layers.Flatten()(h)
    h = layers.Dense(16, activation="relu")(h)

    #vae
    z_mean = layers.Dense(latent_dim, name='z_mean')(h)
    z_log_var = layers.Dense(latent_dim, name='z_log_var')(h)
    z = Sampling()([z_mean, z_log_var])
    encoder = tf.keras.Model(inputs, [z_mean, z_log_var, z], name='encoder')
    encoder.summary()

    #decoder
    latent_inputs = tf.keras.Input(shape=(latent_dim,))
    h = layers.Dense(1 * 5 * 128, activation="relu")(latent_inputs)
    h = layers.Reshape((128, 1, 5))(h)
    h = layers.Conv2DTranspose(64, kernel_size=(2, 4), strides=(2, 2), padding='valid', activation=tf.keras.activations.relu, data_format="channels_first")(h)
    h = layers.Conv2DTranspose(32, kernel_size=(2, 4), strides=(2, 2), padding='valid', activation=tf.keras.activations.relu,
                      data_format="channels_first")(h)
    decoder_outputs = layers.Conv2DTranspose(1, kernel_size=(2, 4), strides=(2, 2), activation="sigmoid", padding="valid",
                                             data_format="channels_first")(h)
    decoder = tf.keras.Model(latent_inputs, decoder_outputs, name="decoder")
    decoder.summary()


    class VAE(tf.keras.Model):
        def __init__(self, encoder, decoder, **kwargs):
            super(VAE, self).__init__(**kwargs)
            self.encoder = encoder
            self.decoder = decoder
            self.total_loss_tracker = tf.keras.metrics.Mean(name="total_loss")
            self.reconstruction_loss_tracker = tf.keras.metrics.Mean(
                name="reconstruction_loss"
            )
            self.kl_loss_tracker = tf.keras.metrics.Mean(name="kl_loss")

        @property
        def metrics(self):
            return [
                self.total_loss_tracker,
                self.reconstruction_loss_tracker,
                self.kl_loss_tracker,
            ]

        def train_step(self, data):
            with tf.GradientTape() as tape:
                z_mean, z_log_var, z = self.encoder(data)
                reconstruction = self.decoder(z)
                reconstruction_loss = tf.reduce_mean(
                    tf.reduce_sum(
                        tf.keras.losses.binary_crossentropy(data, reconstruction), axis=(1, 2)
                    )
                )
                kl_loss = -0.5 * (1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var))
                kl_loss = tf.reduce_mean(tf.reduce_sum(kl_loss, axis=1))
                total_loss = reconstruction_loss + kl_loss
            grads = tape.gradient(total_loss, self.trainable_weights)
            self.optimizer.apply_gradients(zip(grads, self.trainable_weights))
            self.total_loss_tracker.update_state(total_loss)
            self.reconstruction_loss_tracker.update_state(reconstruction_loss)
            self.kl_loss_tracker.update_state(kl_loss)
            return {
                "loss": self.total_loss_tracker.result(),
                "reconstruction_loss": self.reconstruction_loss_tracker.result(),
                "kl_loss": self.kl_loss_tracker.result(),
            }



    vae = VAE(encoder, decoder)
    #vae.compile(optimizer=tf.keras.optimizers.Adam())
    #vae.fit(x_train, epochs=5, batch_size=128)

    a,b,c=vae.encoder.predict(x_train)

ModuleNotFoundError: No module named 'absl'